### ISSUE TITLE
Github projects api is unstable

### ISSUE THREAD

**Issue by sjeohp** [paritytech/parity-processbot#143]
Cannot rely on getting the column via `column_url`

**Comment by sjeohp** [comment]
If a change of Project goes unconfirmed or denied by the project owner, the change should be reverted.  This seems to require deleting a ProjectCard, but fails as the app `Must have admin rights to Repository.`  Additional app permissions do not help.

The Projects API is unstable so this may be a consequence of that.

**Comment by joao-paulo-parity** [comment]
`column_url` is "required" according to the specification published in [rest-api-description](https://github.com/github/rest-api-description/tree/main/descriptions/ghes-3.0). Maybe the API has stabilized in the past year.

I've not seen any issue related to `column_url` pop up in production.  Will re-open with an real report from the logs if it comes to that. As it is, it's not actionable since it doesn't describe when `column_url` might be missing.
