### ISSUE TITLE
Polkadot/substrate lock-step merges

### ISSUE THREAD

**Issue by sjeohp** [paritytech/parity-processbot#157]
https://github.com/paritytech/devops/issues/475

Polkadot master should always be up to date with substrate master.

Example of a substrate pr with companion polkadot pr: https://github.com/paritytech/substrate/pull/5695

**Comment by gnunicorn** [comment]
lock stepping means:

1. any PR that has a companion needs to have `mergeoncegreen` on both this and the companion PR
2. when the CI passed on a PR where that is the case, the Bot will squash merge it into substrate master
3. And then update the companion PR to use latest substrate master (by effectively running `cargo update -p sp-io && git commit -a -m 'Update for Substrate #...' Cargo.lock && git push`)
4. Squash-Merge the companion PR into polkadot.

re 4: as the companion PR is a mandatory CI check on substrate, there is no need to wait for another CI run before merging polkadot. Rather, because the CI run would delay the merge,  other things could be merged in between and complicate things. Hence our current thinking of allowing the bot to merge right away.

**Comment by gabreal** [comment]
if 3.) cannot easily be done by the bot a ci job can do it for instance if a commit on master was from a pr which had a certain label or comment.

**Comment by sjeohp** [comment]
Closed in #201
