### ISSUE TITLE
Don't fail with "check that the PR belongs to a project column."

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-processbot#212]
Example: https://github.com/paritytech/polkadot/pull/1571

Please don't return an error in this case and assume only 1 review is required.

**Comment by rphmeier** [comment]
Yeah, there should be default or fallback configuration for issues that are not in a project. We don't even use projects that much in Parity so there shouldn't be this hard requirement for us to use them.

**Comment by ordian** [comment]
I assume is related to Process.json file: https://github.com/paritytech/polkadot/blob/master/Process.json, but we use projects only for issues, not PRs, at least in Polkadot, so yeah, please provide a fallback.

**Comment by sjeohp** [comment]
- If paritytech/polkadot#1571 was tagged `insubstantial` it would have been merged (one `core-dev` approval is enough).
- If @rphmeier had requested the merge, it would have been merged (request from a `substrateteamlead`).

Otherwise the possibilities that occur to me are:
- Allow merging any PR with a single `core-dev` approval.  I believe this would not be a welcome change on Substrate though.
- Allow merging with a single `substrateteamlead` approval.  This might make sense.  Currently `substrateteamlead`s can request a merge (mainly so that @bkchr and anyone else who is not a listed project owner could merge) so an approval should also suffice.

**Comment by ordian** [comment]
Thanks for the insight, so would it have been merged if the PR had 2 approvals? It wasn't clear from the error message, I would suggest changing the message to something more user-friendly.

We don't use `insubstantial` tags for code changes as per https://github.com/paritytech/polkadot/pull/1413#issuecomment-658904044.

> Allow merging with a single substrateteamlead approval. Currently substrateteamleads can request a merge (mainly so that bkchr and anyone else who is not a listed project owner could merge) so an approval should probably also suffice.

I think this is a viable option.

**Comment by sjeohp** [comment]
> Thanks for the insight, so would it have been merged if the PR had 2 approvals? It wasn't clear from the error message, I would suggest changing the message to something more user-friendly.

Correct and noted, thanks.

**Comment by sjeohp** [comment]
> Allow merging with a single substrateteamlead approval.

This is implemented.
