### ISSUE TITLE
Companions should not be checked twice before merging

### ISSUE THREAD

**Issue by sjeohp-zz** [paritytech/parity-processbot#213]
If a companion PR has been checked by `check-polkadot-companion-build` already, Processbot should not wait for checks again before merging.

**Comment by joao-paulo-parity** [comment]
> Processbot should not wait for checks again before merging

New checks are triggered because the bot does ["update Substrate" commit](https://github.com/paritytech/parity-processbot/blob/85a4862becd550727d6bd465fc30bdde04019748/src/companion.rs#L206) before merging. The bot is forced to wait for required status checks after that is done, no matter what, thus there's no way to literally skip CI. It would be possible to skip *the work CI does* by e.g. signaling the pipeline should be a no-op through a "[SKIP CI]" commit message, then the pipeline(s) would simply post a success status without actually running the scripts.

If we find a way to avoid this "update Substrate" commit (the ideal solution), then this issue could be closed.

**Comment by joao-paulo-parity** [comment]
The `check-dependent-*` checks only executes `cargo check`, but the dependents' CI does much more than that (see https://github.com/paritytech/ci_cd/issues/234). For that reason it doesn't make sense to skip the dependent's CI on the basis on that check alone.
