### ISSUE TITLE
'bot merge' errors

### ISSUE THREAD

**Issue by montekki** [paritytech/parity-processbot#219]
Here: https://github.com/paritytech/polkadot/pull/1659#issuecomment-690290296

**Comment by joao-paulo-parity** [comment]
> Network error getting Process.json: error decoding response body: unknown variant connected

My findings point to a missing variant in the `Event` enum

https://github.com/paritytech/parity-processbot/blob/dee4d2479cdbbf835160b26712203455b39eb21b/src/github.rs#L218

Obvious fix: add the variant.

Problems with it:

- Does not fix the underlying issue of having to manually keep up with the Github API.
- It's not a proper fix to avoid the failure ahead-of-time, since we only know it's broken when it fails.

The latest variants are always updated in [issue-event-types.md](https://github.com/github/docs/blob/436345792fd723cdf1467a5fc18bdd3fed2a7d28/content/developers/webhooks-and-events/issue-event-types.md), which is used to generate [the web page](https://docs.github.com/en/developers/webhooks-and-events/issue-event-types). A good fix would be having a Bot automatically warn (e.g. through a new issue) whenever changes in that file are detected for type inclusions/exclusions, similar to what [octokitbot does](https://github.com/octokit/types.ts/pull/273/files).

Regardless, my plan is to submit the manual patch in a merge request. The bot idea can be brought up later.

**Comment by joao-paulo-parity** [comment]
> Until the long-term fix is implemented, can we simply ignore unknown variants if we only care about a fixed set a events that are not likely to change?

That's a good idea, although the test suite doesn't have great coverage, so it's harder to say for certain which variants are used without going through the whole code. I'll try to do that, though.

Also have to take a look at why this enum is being parsed at all for comment interactions since [the relevant event](https://docs.github.com/en/developers/webhooks-and-events/github-event-types#issuecommentevent) does not include it.
